name: Deploy Streamlit App

on:
  push:
    branches: [ main ]  # Runs on push to main branch
  pull_request:
    branches: [ main ]  # Runs on PRs to main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Linux environment required for libGL
    
    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install system dependencies (fixes libGL.so.1)
      - name: Install OpenGL libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgl1 \
            libglib2.0-0 \
            libsm6 \
            libxrender1 \
            libxext6

      # Step 3: Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 4: Install Python dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          # Force headless OpenCV if needed
          pip install opencv-python-headless

      # Step 5: Run Streamlit (for testing)
      - name: Test Streamlit app
        run: |
          streamlit run app.py --server.port 8080 &
          sleep 5  # Wait for server to start
          curl http://localhost:8080/healthz  # Verify server is up